[server]
port=8502 
baseUrlPath = "ritehealth"
headless=true 
#enableCORS=false
#enableXsrfProtection=false
#enableWebsocketCompression=false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
